# Generated by Django 4.1 on 2022-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_refeicao_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='img',
            field=models.ImageField(default=1, upload_to='paciente'),
            preserve_default=False,
        ),
    ]
