# Generated by Django 3.2.12 on 2023-01-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_pacientes_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='img',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='perfil',
            field=models.ImageField(null=True, upload_to='perfil'),
        ),
    ]
